refactor(clerk-js): Pick the redirection prop using a more intuitive approach
clerk/javascript pull request #1680
Opened 2023-09-04 13:27 UTC by desiprisg

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

This is a proposed refactor to make the choosing of the redirect url a more intuitive process. The new function accepts keys and the sources to choose them from, in order. A validator and formatter can also be added.

Initially, this was done as part of a PR that also added some new query params for org actions, but since more logic has been added by the orgs team, I'll leave that up to them to implement. It should be relativelt easy to do after this refactor.

2023-09-05 09:07 UTC, desiprisg commented on packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
> +    }) || pickUrl(['afterSignUpUrl', 'redirectUrl'], [ctx, options, displayConfig]),
This is done because we want to add a validator only for the query parameters.

2023-09-28 20:35 UTC, SokratisVidros commented
What's the status of this PR? @octoper are you working on it?

2023-09-29 12:48 UTC, dimkl commented on packages/clerk-js/src/core/clerk.ts
> +      afterSignUpUrl: pickUrl('afterSignUpUrl', [options, this.#options]),
❓ @desiprisg is the `pickUrl()` fallbacks to `queryParams.redirect_url` or `options.redirectUrl` that the `pickRedirectionProp` was?

2023-09-29 12:54 UTC, dimkl commented on packages/clerk-js/src/ui/contexts/ClerkUIComponentsContext.tsx
> +    }) || pickUrl(['afterSignInUrl', 'redirectUrl'], [ctx, options, displayConfig]),
☁️ i think that it's a great idea to refactor the `pickRedirectionProp` to something simpler and more maintainable than currently is but the above code (personal preference) does not make it easier for me to understand the rules of picking the `afterSignInUrl`. :(

2023-09-30 09:39 UTC, octoper commented
@SokratisVidros No I accidentaly closed it through another PR.

2023-11-09 14:15 UTC, nikosdouvlis requested changes
@desiprisg You will need to apply the changes to the ui-retheme dir.  I will share more details within the day

2023-12-29 18:03 UTC, clerk-cookie commented
Hello 👋

We currently close PRs after 60 days of inactivity. It's been 50 days since the last update here. If we missed this PR, please reply here. Otherwise, we'll close this PR in 10 days.

Thanks for being a part of the Clerk community! 🙏

2024-01-08 18:03 UTC, clerk-cookie commented
Hello again 👋

After 60 days of no activity, we'll close this PR. Keep in mind, I'm just a robot, so if I've closed this PR in error, please reply here and my human colleagues will reopen it.

Thanks for being a part of the Clerk community! 🙏

2024-01-08 18:03 UTC, closed without merging