chore(repo): Deprecate node@{14,15,16,17 versions
clerk/javascript pull request #1864
Opened 2023-10-11 14:59 UTC by dimkl

## Description

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

2023-10-12 08:19 UTC, nikosdouvlis commented
> It would be good to add the `engines` field to all packages, e.g. `shared` is missing that information
> 
> For our reasoning why we chose Node 18 we should use https://github.com/nodejs/release#release-schedule for our changelog. We'll just follow the LTS plan

The reason we chose Node 18 for the v5 release is outlined here: https://nodejs.org/en/blog/announcements/nodejs16-eol?mkt_tok=MDAxLUxSRy0xOTQAAAGMUL0csiUbl5CDLnZeh6VUFzAi-55IRjUjdJFK08bCgi-8udk1gxib7nWjYJZzdt-f7Y8YRS_MxsvPa9_gml4IeZxVmqc2TDPcO-KNkEyr

2023-11-06 08:30 UTC, LekoArts requested changes

2023-11-06 08:30 UTC, LekoArts commented on packages/backend/README.md
> +Works on Node.js `^18.18` (or later) or on any V8 Isolates runtimes (eg Cloudflare Workers).
In the README you write `^18.18` but in the `engines` field we have `>=18`.

Currently that would mean we allow `^18.0.0`. So if you want to have `^18.18` you'll need to adjust the `engines` field everywhere.

2023-11-06 08:30 UTC, LekoArts commented on .changeset/purple-pumas-study.md
> +and introduced `isomorphicBtoa` helper in `@clerk/shared`.
```suggestion
Dropping support for Node 14 and 16 as they both reached EOL status. The minimal Node.js version required by Clerk is `18.18.0` now.
```

For the new helper in `@clerk/shared` you can add a new changeset with a `minor`

2023-11-06 08:30 UTC, LekoArts commented on integration/templates/react-cra/package.json
> +    "@types/node": "^18.18",
Nit: You write `18.18` everywhere but it would be better to also have the patch version everywhere. So if you mean `18.18.0` then use that

2023-11-06 08:54 UTC, dimkl commented
@LekoArts : I will update the `@types/node`, `engines` and the README to `^18.18.0` everywhere since the v18 has entered maintenance mode and there probably won't ever be a `v18.19`.

2023-11-06 10:55 UTC, dimkl commented
@LekoArts changes applied, ptal.

2023-11-06 12:40 UTC, merged