[WIP] chore(clerk-js): Introduce Form.PasswordInput, InputGroup, Checkbox
clerk/javascript pull request #2087
Opened 2023-11-08 17:38 UTC by panteliselef

## Description

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

2023-11-09 14:14 UTC, nikosdouvlis requested changes
@panteliselef You will need to apply these changes to the ui-retheme directory. I will share more info within the day

2023-11-13 11:20 UTC, panteliselef commented
> @panteliselef You will need to apply these changes to the ui-retheme directory. I will share more info within the day

@nikosdouvlis Do u mind unblocking this ? The changes u requested have been pushed.

2023-11-16 09:11 UTC, nikosdouvlis approved these changes

2023-11-16 09:18 UTC, dimkl approved these changes

2023-11-16 11:00 UTC, merged