feat(clerk-js): Retheme card action destructive variant
clerk/javascript pull request #2394
Opened 2023-12-18 19:31 UTC by marcelscruz

## Description

Added a rethemed variant for the action card.

<img width="604" alt="Screenshot 2023-12-18 at 16 30 44" src="https://github.com/clerk/javascript/assets/12413903/51d5ce71-5e45-4d77-abd5-4dc7f7e324b8">

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

2023-12-18 19:57 UTC, octoper approved these changes
💯

2023-12-18 19:58 UTC, anagstef commented on packages/clerk-js/src/ui/elements/Action/ActionCard.tsx
> +  isDestructive?: boolean;
For consistency, we should go with:
```suggestion
  variant?: 'neutral' | 'destructive';
```

2023-12-18 20:02 UTC, marcelscruz commented on packages/clerk-js/src/ui/elements/Action/ActionCard.tsx
> +  isDestructive?: boolean;
Updated.

2023-12-19 08:48 UTC, desiprisg requested changes
Let's apply the variant to org profile screens as well!

2023-12-19 16:41 UTC, anagstef approved these changes

2023-12-19 17:08 UTC, merged