feat(elements): Add temporary useIsLoading hook
clerk/javascript pull request #2751
Opened 2024-02-07 13:36 UTC by LekoArts

## Description

While in https://github.com/clerk/javascript/pull/2669 Bryce started implementing a holistic solution, for the Alpha stage we'll opt to providing a temporary `unstable_useIsLoading` hook. Took some bits from https://github.com/clerk/javascript/pull/2669 that were useful in any way 👍 

Once we have thought more about the API for loading states we'll remove this again and tackle the proper solution.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/backend`
- [ ] `@clerk/chrome-extension`
- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `@clerk/localizations`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/themes`
- [ ] `@clerk/types`
- [ ] `build/tooling/chore`

2024-02-07 13:37 UTC, LekoArts commented on packages/elements/src/internals/machines/sign-in/sign-in.machine.ts
> +      tags: ['state:start'],
XState docs use arrays (https://stately.ai/docs/tags) and might be a good idea to just follow that, too

2024-02-14 14:49 UTC, tmilewski requested changes

2024-02-14 14:49 UTC, tmilewski commented on packages/elements/src/react/hooks/use-loading.hook.ts
> +export const unstable_useIsLoading = () => {
To keep with React hook naming conventions:


```suggestion
export const useIsLoading_unstable = () => {
```

2024-02-14 14:49 UTC, tmilewski commented on packages/elements/src/react/hooks/use-loading.hook.ts
> +  return [isGlobalLoading, { start: startLoading, firstFactor: firstFactorLoading, secondFactor: secondFactorLoading }];
Likely a cleaner/clearer way to handle this in the long-run, but cool for now. On concern though is that it's specific to signIn, and lives in the root React hooks. Mind moving it over?

2024-02-14 14:57 UTC, tmilewski approved these changes

2024-02-14 15:12 UTC, merged