Update profile primary button text and nav text in fr-FR & zh-CN
clerk/javascript pull request #3494
Opened 2024-06-01 21:07 UTC by youshengCode

## Description

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-06-03 15:51 UTC, LauraBeatris requested changes
@youshengCode Thanks for your contribution! It's looking good, only missing a changeset.

Could you add it based on the instructions on [CONTRIBUTING.md](https://github.com/clerk/javascript/blob/main/docs/CONTRIBUTING.md#changesets)? Thanks!

2024-06-04 09:00 UTC, dimkl approved these changes

2024-06-04 14:02 UTC, LauraBeatris approved these changes

2024-06-04 17:49 UTC, tmilewski approved these changes

2024-06-05 09:42 UTC, merged