feat(localizations): Add support for German (de-DE) passkey-text localization
clerk/javascript pull request #3695
Opened 2024-07-11 17:58 UTC by navid-rji

## Description
The code changes add support for the German passkey-text localization and translations for some texts that haven't been translated.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [x] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-07-12 07:23 UTC, LekoArts requested changes
Thanks for the PR! Some smaller adjustments are needed and then it's good to go 👍

2024-07-12 07:23 UTC, LekoArts commented on packages/localizations/src/de-DE.ts
> +      actionLink__use_passkey: 'Stattdessen Passkey verwenden',
Let's make it shorter

```suggestion
      actionLink__use_passkey: 'Passkey nutzen',
```

2024-07-12 07:23 UTC, LekoArts commented on packages/localizations/src/de-DE.ts
> +    form_identifier_exists__username: 'Dieser Benutzername ist bereits vergeben. Bitte wählen Sie einen Anderen.',
```suggestion
    form_identifier_exists__email_address: 'Diese E-Mail-Adresse ist bereits vergeben. Bitte wählen Sie eine andere.',
    form_identifier_exists__phone_number: 'Diese Telefonnummer ist bereits vergeben. Bitte wählen Sie eine andere.',
    form_identifier_exists__username: 'Dieser Benutzername ist bereits vergeben. Bitte wählen Sie einen anderen.',
```

2024-07-12 07:23 UTC, LekoArts commented on packages/localizations/src/de-DE.ts
> +    form_password_pwned__sign_in: 'Dieses Passwort wurde in einem Datenlecks gefunden und kann nicht verwendet werden. Bitte setzen Sie Ihr Passwort zurück.',
```suggestion
    form_password_pwned__sign_in: 'Dieses Passwort wurde in einem Datenleck gefunden und kann nicht verwendet werden. Bitte setzen Sie Ihr Passwort zurück.',
```

2024-07-12 07:23 UTC, LekoArts commented on packages/localizations/src/de-DE.ts
> +    passkey_retrieval_cancelled: 'Passkey verification was cancelled or timed out.',
```suggestion
    passkey_registration_cancelled: 'Die Passkey-Registrierung wurde abgebrochen oder die Zeit wurde überschritten.',
    passkey_retrieval_cancelled: 'Die Passkey-Verifikation wurde abgebrochen oder die Zeit wurde überschritten.',
```

2024-07-12 11:03 UTC, LekoArts approved these changes

2024-07-22 12:26 UTC, dimkl approved these changes

2024-07-23 14:33 UTC, merged