fix(elements): Fix `SignIn.SafeIdentifier` potentially outputting an …
clerk/javascript pull request #3974
Opened 2024-08-16 17:15 UTC by tmilewski

…incorrect value

## Description

Fix `SignIn.SafeIdentifier` potentially outputting an incorrect identifier when using similar multi-session sign in strategies.

Fixes: SDKI-609

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [x] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-08-16 17:43 UTC, alexcarpenter approved these changes

2024-08-16 17:49 UTC, dstaley requested changes

2024-08-16 17:49 UTC, dstaley commented on packages/elements/src/internals/machines/sign-in/router.selectors.ts
> +          ? matchingFactors.find(f => 'safeIdentifier' in f && f.safeIdentifier === signIn.identifier)
Requiring the factor's safeIdentifier to match the user provided identifier results in the user provided identifier being returned for factors in which it's not valid, for example rendering a phone number for `email_code` and `email_link`. Should we maybe break this logic up into two pieces?

```ts
const matchingFactorForIdentifier =
  signIn.identifier && matchingFactors.length > 0
    ? matchingFactors.find(
        (f) => "safeIdentifier" in f && f.safeIdentifier === signIn.identifier
      )
    : null;

const matchingFactorForStrategy = matchingFactors[0];

if (
  matchingFactorForIdentifier &&
  "safeIdentifier" in matchingFactorForIdentifier
) {
  return matchingFactorForIdentifier.safeIdentifier;
} else if (
  matchingFactorForStrategy &&
  "safeIdentifier" in matchingFactorForStrategy
) {
  return matchingFactorForStrategy.safeIdentifier;
}
```

![Screen Shot 2024-08-16 at 10 37 18 AM](https://github.com/user-attachments/assets/e3b62435-563c-49b6-8ce4-7585af4c44aa)

2024-08-16 19:50 UTC, nme22 approved these changes
Approving. I think @dstaley 's mention of breaking this logic up into two spots is a good call.

2024-08-26 20:19 UTC, dstaley approved these changes

2024-08-26 20:19 UTC, merged