Sort organizations list in OrganizationSwitcher
clerk/javascript pull request #4241
Opened 2024-09-29 10:54 UTC by reinert

## Description

`<OrganizationSwitcher/>` displays the organizations in random order by default. It's annoying to find an organization over hundreds of randomly sorted options having no ability to search through them. This simple patch sorts the organization list alphabetically by default to make it feasible for the users to find an org when they have several alternatives.

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-09-30 09:43 UTC, LauraBeatris approved these changes
Thanks @reinert! 

We're aware that this experience can be improved. There's an upcoming feature on our roadmap to introduce search capabilities on `OrganizationSwitcher` 😄

2024-09-30 09:43 UTC, LauraBeatris commented on .changeset/cool-laws-remember.md
> +Sort organizations list in OrganizationSwitcher
```suggestion
Sort organizations list alphabetically in `OrganizationSwitcher`
```

2024-09-30 09:51 UTC, LauraBeatris requested changes
Hi @reinert! We need to perform some adjustments here to handle the server-side rendering case.

2024-09-30 10:20 UTC, panteliselef commented
As @LauraBeatris mentioned we will improve the `<OrganizationSwitcher/>` soon. Having said that we appreciate your efforts and pushing us to improve the UX here.

Here's the issues I see with the proposed solution from this PR:
- (Optionally) Make it opt-in, so folks understand what has changed. (e.g Control via a prop or UI button)
- Do this server side. With the implementation of this PR and due to pagination, an end-user may end up fetching the next batch and cause layout shifts as orgs will not necessary be appended, but may end up between existing ones. Also there is a chance that the user may end up missing them (the newly fetched orgs), if the've scrolled but an org is added at the top due to the client side sorting.

Since this requires more changes to be made in the codebase, I propose letting us to take over and make sure that the above will be resolved before shipping this to everyone. (We might need to make changes in parts that are not available to OSS contributors)

2024-09-30 11:46 UTC, reinert commented
Thanks guys for the feedback. Do we have any ETA regarding those improvements in the OrganizationSwitcher component. This unsorted listing is causing us several issues like may tickets being submitted to our support channel. It's a daily pain for our back-office and a cost that's increasing exponentially. We really need an immediate workaround at least if we can't have a definitive solution soon. I really appreciate your timely response.

2024-09-30 14:59 UTC, panteliselef commented
!snapshot

2024-09-30 15:02 UTC, clerk-cookie commented
Hey @panteliselef - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/chrome-extension | 1.3.13-snapshot.vf979cb7 |
| @clerk/clerk-js | 5.24.2-snapshot.vf979cb7 |
| @clerk/clerk-expo | 2.2.19-snapshot.vf979cb7 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.13-snapshot.vf979cb7 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.24.2-snapshot.vf979cb7 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.2.19-snapshot.vf979cb7 --save-exact
```

2024-09-30 15:46 UTC, reinert commented
Thank you @panteliselef. Do we have the ability to quickly lookup for one organization over several alternatives in this snapshot version? (otherwise pagination is going to cause even more pain in this scenario)

2024-09-30 17:49 UTC, panteliselef commented
This snapshot only includes the solution from this PR

2024-09-30 19:26 UTC, reinert commented
Oh, great, I got it. Thanks @panteliselef. Gonna try it out.

2024-10-01 15:53 UTC, LauraBeatris commented
@reinert We're working on a frontend API change to alphabetically order organization memberships by default. This should be shipped by the beginning of next week and it won't require updating your SDK code, just keep using `OrganizationSwitcher` as it is atm.

2024-10-01 16:30 UTC, reinert commented
Thanks for the feedback @LauraBeatris. Really appreciate the effort to solve this issue.

2024-10-01 16:46 UTC, reinert commented
May I close this PR?

2024-10-01 17:37 UTC, LauraBeatris commented
@reinert Closing this PR, I'll @ you here once those changes are deployed.

2024-10-01 17:37 UTC, closed without merging

2024-10-02 09:49 UTC, LauraBeatris commented
@reinert We've deployed that change, could you give it a try and let us know?