Feat/expo passkeys [WIP]
clerk/javascript pull request #4352
Opened 2024-10-17 15:24 UTC by AlexNti

## Description

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-10-18 08:39 UTC, AlexNti commented
!snapshot

2024-10-18 08:46 UTC, AlexNti commented
!snapshot

2024-10-18 08:49 UTC, AlexNti commented
!snapshot

2024-10-18 08:53 UTC, clerk-cookie commented
Hey @AlexNti - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.3.16-snapshot.v84a6da3 |
| @clerk/backend | 1.14.1-snapshot.v84a6da3 |
| @clerk/express | 1.3.1-snapshot.v84a6da3 |
| @clerk/fastify | 2.0.3-snapshot.v84a6da3 |
| @clerk/nextjs | 5.7.5-snapshot.v84a6da3 |
| @clerk/remix | 4.2.39-snapshot.v84a6da3 |
| @clerk/clerk-sdk-node | 5.0.52-snapshot.v84a6da3 |
| @clerk/tanstack-start | 0.4.15-snapshot.v84a6da3 |
| @clerk/testing | 1.3.13-snapshot.v84a6da3 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.3.16-snapshot.v84a6da3 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.14.1-snapshot.v84a6da3 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.1-snapshot.v84a6da3 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.3-snapshot.v84a6da3 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@5.7.5-snapshot.v84a6da3 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.39-snapshot.v84a6da3 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.52-snapshot.v84a6da3 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.15-snapshot.v84a6da3 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.13-snapshot.v84a6da3 --save-exact
```

2024-10-18 09:27 UTC, anagstef commented
!snapshot

2024-10-23 16:28 UTC, AlexNti commented
!snapshot

2024-10-23 16:33 UTC, clerk-cookie commented
Hey @AlexNti - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.4.1-snapshot.v1f5c4b4 |
| @clerk/backend | 1.15.1-snapshot.v1f5c4b4 |
| @clerk/chrome-extension | 1.3.22-snapshot.v1f5c4b4 |
| @clerk/clerk-js | 5.29.0-snapshot.v1f5c4b4 |
| @clerk/elements | 0.17.1-snapshot.v1f5c4b4 |
| @clerk/clerk-expo | 2.3.0-snapshot.v1f5c4b4 |
| @clerk/express | 1.3.3-snapshot.v1f5c4b4 |
| @clerk/fastify | 2.0.5-snapshot.v1f5c4b4 |
| @clerk/localizations | 3.3.2-snapshot.v1f5c4b4 |
| @clerk/nextjs | 6.0.1-snapshot.v1f5c4b4 |
| @clerk/clerk-react | 5.13.1-snapshot.v1f5c4b4 |
| @clerk/remix | 4.2.41-snapshot.v1f5c4b4 |
| @clerk/clerk-sdk-node | 5.0.54-snapshot.v1f5c4b4 |
| @clerk/shared | 2.10.1-snapshot.v1f5c4b4 |
| @clerk/tanstack-start | 0.4.17-snapshot.v1f5c4b4 |
| @clerk/testing | 1.3.15-snapshot.v1f5c4b4 |
| @clerk/themes | 2.1.39-snapshot.v1f5c4b4 |
| @clerk/types | 4.28.0-snapshot.v1f5c4b4 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.4.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.15.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.22-snapshot.v1f5c4b4 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.29.0-snapshot.v1f5c4b4 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.17.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.3.0-snapshot.v1f5c4b4 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.3-snapshot.v1f5c4b4 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.5-snapshot.v1f5c4b4 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.3.2-snapshot.v1f5c4b4 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.0.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.13.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.41-snapshot.v1f5c4b4 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.54-snapshot.v1f5c4b4 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.10.1-snapshot.v1f5c4b4 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.17-snapshot.v1f5c4b4 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.15-snapshot.v1f5c4b4 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.39-snapshot.v1f5c4b4 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.28.0-snapshot.v1f5c4b4 --save-exact
```

2024-10-23 16:43 UTC, AlexNti commented
!snapshot

2024-10-23 16:48 UTC, clerk-cookie commented
Hey @AlexNti - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.4.1-snapshot.va96a299 |
| @clerk/backend | 1.15.1-snapshot.va96a299 |
| @clerk/chrome-extension | 1.3.22-snapshot.va96a299 |
| @clerk/clerk-js | 5.29.0-snapshot.va96a299 |
| @clerk/elements | 0.17.1-snapshot.va96a299 |
| @clerk/clerk-expo | 2.3.0-snapshot.va96a299 |
| @clerk/express | 1.3.3-snapshot.va96a299 |
| @clerk/fastify | 2.0.5-snapshot.va96a299 |
| @clerk/localizations | 3.3.2-snapshot.va96a299 |
| @clerk/nextjs | 6.0.1-snapshot.va96a299 |
| @clerk/clerk-react | 5.13.1-snapshot.va96a299 |
| @clerk/remix | 4.2.41-snapshot.va96a299 |
| @clerk/clerk-sdk-node | 5.0.54-snapshot.va96a299 |
| @clerk/shared | 2.10.1-snapshot.va96a299 |
| @clerk/tanstack-start | 0.4.17-snapshot.va96a299 |
| @clerk/testing | 1.3.15-snapshot.va96a299 |
| @clerk/themes | 2.1.39-snapshot.va96a299 |
| @clerk/types | 4.28.0-snapshot.va96a299 |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.4.1-snapshot.va96a299 --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.15.1-snapshot.va96a299 --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.22-snapshot.va96a299 --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.29.0-snapshot.va96a299 --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.17.1-snapshot.va96a299 --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.3.0-snapshot.va96a299 --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.3-snapshot.va96a299 --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.5-snapshot.va96a299 --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.3.2-snapshot.va96a299 --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.0.1-snapshot.va96a299 --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.13.1-snapshot.va96a299 --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.41-snapshot.va96a299 --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.54-snapshot.va96a299 --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.10.1-snapshot.va96a299 --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.17-snapshot.va96a299 --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.15-snapshot.va96a299 --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.39-snapshot.va96a299 --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.28.0-snapshot.va96a299 --save-exact
```

2024-10-23 18:52 UTC, AlexNti commented
!snapshot

2024-10-23 18:59 UTC, AlexNti commented
!snapshot

2024-10-23 19:04 UTC, clerk-cookie commented
Hey @AlexNti - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.4.1-snapshot.vb92f3ea |
| @clerk/backend | 1.15.1-snapshot.vb92f3ea |
| @clerk/chrome-extension | 1.3.22-snapshot.vb92f3ea |
| @clerk/clerk-js | 5.29.0-snapshot.vb92f3ea |
| @clerk/elements | 0.17.1-snapshot.vb92f3ea |
| @clerk/clerk-expo | 2.3.0-snapshot.vb92f3ea |
| @clerk/express | 1.3.3-snapshot.vb92f3ea |
| @clerk/fastify | 2.0.5-snapshot.vb92f3ea |
| @clerk/localizations | 3.3.2-snapshot.vb92f3ea |
| @clerk/nextjs | 6.0.1-snapshot.vb92f3ea |
| @clerk/clerk-react | 5.13.1-snapshot.vb92f3ea |
| @clerk/remix | 4.2.41-snapshot.vb92f3ea |
| @clerk/clerk-sdk-node | 5.0.54-snapshot.vb92f3ea |
| @clerk/shared | 2.10.1-snapshot.vb92f3ea |
| @clerk/tanstack-start | 0.4.17-snapshot.vb92f3ea |
| @clerk/testing | 1.3.15-snapshot.vb92f3ea |
| @clerk/themes | 2.1.39-snapshot.vb92f3ea |
| @clerk/types | 4.28.0-snapshot.vb92f3ea |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.4.1-snapshot.vb92f3ea --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.15.1-snapshot.vb92f3ea --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.22-snapshot.vb92f3ea --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.29.0-snapshot.vb92f3ea --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.17.1-snapshot.vb92f3ea --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.3.0-snapshot.vb92f3ea --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.3-snapshot.vb92f3ea --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.5-snapshot.vb92f3ea --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.3.2-snapshot.vb92f3ea --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.0.1-snapshot.vb92f3ea --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.13.1-snapshot.vb92f3ea --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.41-snapshot.vb92f3ea --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.54-snapshot.vb92f3ea --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.10.1-snapshot.vb92f3ea --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.17-snapshot.vb92f3ea --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.15-snapshot.vb92f3ea --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.39-snapshot.vb92f3ea --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.28.0-snapshot.vb92f3ea --save-exact
```

2024-10-23 20:25 UTC, AlexNti commented
!snapshot

2024-10-23 20:32 UTC, clerk-cookie commented
Hey @AlexNti - the snapshot version command generated the following package versions:
| Package | Version |
| --- | --- |
| @clerk/astro | 1.4.1-snapshot.vaa1630d |
| @clerk/backend | 1.15.1-snapshot.vaa1630d |
| @clerk/chrome-extension | 1.3.22-snapshot.vaa1630d |
| @clerk/clerk-js | 5.29.0-snapshot.vaa1630d |
| @clerk/elements | 0.17.1-snapshot.vaa1630d |
| @clerk/clerk-expo | 2.3.0-snapshot.vaa1630d |
| @clerk/express | 1.3.3-snapshot.vaa1630d |
| @clerk/fastify | 2.0.5-snapshot.vaa1630d |
| @clerk/localizations | 3.3.2-snapshot.vaa1630d |
| @clerk/nextjs | 6.0.1-snapshot.vaa1630d |
| @clerk/clerk-react | 5.13.1-snapshot.vaa1630d |
| @clerk/remix | 4.2.41-snapshot.vaa1630d |
| @clerk/clerk-sdk-node | 5.0.54-snapshot.vaa1630d |
| @clerk/shared | 2.10.1-snapshot.vaa1630d |
| @clerk/tanstack-start | 0.4.17-snapshot.vaa1630d |
| @clerk/testing | 1.3.15-snapshot.vaa1630d |
| @clerk/themes | 2.1.39-snapshot.vaa1630d |
| @clerk/types | 4.28.0-snapshot.vaa1630d |

Tip: Use the snippet copy button below to quickly install the required packages.
`@clerk/astro`
```sh
npm i @clerk/astro@1.4.1-snapshot.vaa1630d --save-exact
```
`@clerk/backend`
```sh
npm i @clerk/backend@1.15.1-snapshot.vaa1630d --save-exact
```
`@clerk/chrome-extension`
```sh
npm i @clerk/chrome-extension@1.3.22-snapshot.vaa1630d --save-exact
```
`@clerk/clerk-js`
```sh
npm i @clerk/clerk-js@5.29.0-snapshot.vaa1630d --save-exact
```
`@clerk/elements`
```sh
npm i @clerk/elements@0.17.1-snapshot.vaa1630d --save-exact
```
`@clerk/clerk-expo`
```sh
npm i @clerk/clerk-expo@2.3.0-snapshot.vaa1630d --save-exact
```
`@clerk/express`
```sh
npm i @clerk/express@1.3.3-snapshot.vaa1630d --save-exact
```
`@clerk/fastify`
```sh
npm i @clerk/fastify@2.0.5-snapshot.vaa1630d --save-exact
```
`@clerk/localizations`
```sh
npm i @clerk/localizations@3.3.2-snapshot.vaa1630d --save-exact
```
`@clerk/nextjs`
```sh
npm i @clerk/nextjs@6.0.1-snapshot.vaa1630d --save-exact
```
`@clerk/clerk-react`
```sh
npm i @clerk/clerk-react@5.13.1-snapshot.vaa1630d --save-exact
```
`@clerk/remix`
```sh
npm i @clerk/remix@4.2.41-snapshot.vaa1630d --save-exact
```
`@clerk/clerk-sdk-node`
```sh
npm i @clerk/clerk-sdk-node@5.0.54-snapshot.vaa1630d --save-exact
```
`@clerk/shared`
```sh
npm i @clerk/shared@2.10.1-snapshot.vaa1630d --save-exact
```
`@clerk/tanstack-start`
```sh
npm i @clerk/tanstack-start@0.4.17-snapshot.vaa1630d --save-exact
```
`@clerk/testing`
```sh
npm i @clerk/testing@1.3.15-snapshot.vaa1630d --save-exact
```
`@clerk/themes`
```sh
npm i @clerk/themes@2.1.39-snapshot.vaa1630d --save-exact
```
`@clerk/types`
```sh
npm i @clerk/types@4.28.0-snapshot.vaa1630d --save-exact
```

2024-11-01 13:20 UTC, anagstef commented on packages/clerk-js/src/core/clerk.ts
> +  public __unstable__isWebAuthnPlatformAuthenticatorSupported: (() => Promise<boolean>) | undefined;
We should go for `__experimental_` instead of the `unstable` keyword!

2024-11-01 13:23 UTC, anagstef commented on packages/clerk-js/src/core/clerk.ts
> +  public __unstable__isWebAuthnPlatformAuthenticatorSupported: (() => Promise<boolean>) | undefined;
e.g.
```suggestion
  public __experimental_createPublicCredentials:
    | ((
        publicKey: PublicKeyCredentialCreationOptionsWithoutExtensions,
      ) => Promise<CredentialReturn<PublicKeyCredentialWithAuthenticatorAttestationResponse>>)
    | undefined;

  public __experimental_getPublicCredentials:
    | (({
        publicKeyOptions,
      }: {
        publicKeyOptions: PublicKeyCredentialRequestOptionsWithoutExtensions;
      }) => Promise<CredentialReturn<PublicKeyCredentialWithAuthenticatorAssertionResponse>>)
    | undefined;

  public __experimental_isWebAuthnSupported: (() => boolean) | undefined;
  public __experimental_isWebAuthnAutofillSupported: (() => Promise<boolean>) | undefined;
  public __experimental_isWebAuthnPlatformAuthenticatorSupported: (() => Promise<boolean>) | undefined;
```

2024-11-01 13:29 UTC, anagstef commented on packages/clerk-js/src/core/resources/SignIn.ts
> +    const _isWebAuthnSupported = SignIn.clerk.__unstable__isWebAuthnSupported || isWebAuthnSupported;
To make it more readable I would prefer that we rename on import and keep the initial value name without the underscore. 
Example:
```
import { isWebAuthnSupported as isWebAuthnSupportedOnWindow } from '@clerk/shared/webauthn';

// and then
const isWebAuthnSupported = SignIn.clerk.__unstable__isWebAuthnSupported || isWebAuthnSupportedOnWindow;
```

2024-11-01 13:29 UTC, anagstef commented on packages/clerk-js/src/core/resources/SignIn.ts
> +      SignIn.clerk.__unstable__isWebAuthnAutofillSupported || isWebAuthnAutofillSupported;
Same as above!

2024-11-01 13:34 UTC, anagstef commented on packages/expo/src/provider/singleton/createClerkInstance.ts
> +        __internal_clerk.__unstable__createPublicCredentials = (
Also change these with the `__experimental_`

2024-11-01 13:36 UTC, anagstef commented on packages/expo/src/provider/singleton/createClerkInstance.ts
> +          return Promise.resolve(true);
Is this always true?

2024-11-01 13:38 UTC, AlexNti commented on packages/expo/src/provider/singleton/createClerkInstance.ts
> +          return Promise.resolve(true);
For devices will always be true.

2024-11-01 13:45 UTC, anagstef commented on packages/expo/src/provider/ClerkProvider.tsx
> +  passkeys?: BuildClerkOptions['passkeys'];
Also let's add a comment here that mentions that this is experimental feature etc.

2024-11-01 13:49 UTC, AlexNti commented
> We should use the `__experimental_` prefix because we don't use the `__unstable_` anymore!
> 
> Great job! 🚀

 Thank you for the review @anagstef , how about instead of renaming them from `unstable` to `internal`?

2024-11-01 13:56 UTC, anagstef commented
> > We should use the `__experimental_` prefix because we don't use the `__unstable_` anymore!
> > Great job! 🚀
> 
> Thank you for the review @anagstef , how about instead of renaming them from `unstable` to `internal`?

Yes, that's even better! Let's go with `internal` instead of `unstable`, and use the `experimental` on the public-facing props!

2024-11-04 08:58 UTC, anagstef requested changes
We need to convert:
- `__experimental__XXX` to `__experimental_XXX`
- `__internal__XXX` to `__internal_XXX`

As our convention uses 1 underscore after the `experimental/internal` word.

2024-11-04 08:58 UTC, anagstef commented on .changeset/late-camels-talk.md
> +Introduce support for passkeys in Expo (iOS, Android, and Web).
```suggestion
Introduce expoerimental support for passkeys in Expo (iOS, Android, and Web).
```

2024-11-04 08:58 UTC, anagstef commented on .changeset/late-camels-talk.md
> +<ClerkProvider __experimental__passkeys={passkeys}>
`__experimental_` needs a single underscore.
```suggestion
<ClerkProvider __experimental_passkeys={passkeys}>
```

2024-11-04 08:58 UTC, anagstef commented on packages/clerk-js/src/core/clerk.ts
> +  public __internal__createPublicCredentials:
Also, `__internal_XXX` needs a single underscore before the variable name.
```suggestion
  public __internal_createPublicCredentials:
```

2024-11-04 11:54 UTC, anagstef approved these changes

2024-11-04 11:54 UTC, anagstef commented on packages/expo/src/provider/singleton/types.ts
> +   */
```suggestion
  /**
   * Note: Passkey support in Expo is currently in a limited rollout phase. 
   * If you're interested in using this feature, please contact us for early access or additional details.
   * 
   * @experimental This API is experimental and may change at any moment.
   */
```

2024-11-04 11:54 UTC, anagstef commented on packages/expo/src/provider/ClerkProvider.tsx
> +  __experimental_passkeys?: BuildClerkOptions['__experimental_passkeys'];
```suggestion
   * @see https://clerk.com/docs/quickstarts/expo#configure-the-token-cache-with-expo
   */
  tokenCache?: TokenCache;
   /**
   * Note: Passkey support in Expo is currently in a limited rollout phase. 
   * If you're interested in using this feature, please contact us for early access or additional details.
   * 
   * @experimental This API is experimental and may change at any moment.
   */
  __experimental_passkeys?: BuildClerkOptions['__experimental_passkeys'];
```

2024-11-06 15:50 UTC, merged