Typo fix
clerk/javascript pull request #4660
Opened 2024-11-26 16:27 UTC by kaftarmery

## Description

## Checklist

- [ ] `pnpm test` runs as expected.
- [ ] `pnpm build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

2024-11-26 17:06 UTC, alexcarpenter reviewed
@kaftarmery good catch.

Will need to update the PR title to the format required. e.g. `fix(clerk-js): Fix typo in outAnimation` as an example.

Will also need to generate a changeset, which can be triggered via `npx changeset` in the repo, and follow the steps. https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md

2024-11-27 08:25 UTC, panteliselef requested changes

2024-11-27 08:25 UTC, panteliselef commented on packages/clerk-js/.changeset/README.md
> +[our documentation](https://github.com/changesets/changesets/blob/main/docs/common-questions.md)
can you revert this and run `pnpm changeset` at the root of the monorepo ?

2024-11-27 08:25 UTC, panteliselef commented on packages/clerk-js/.changeset/config.json
> +}
can you revert this and run pnpm changeset at the root of the monorepo ?

2024-11-27 10:40 UTC, panteliselef approved these changes

2024-11-27 11:17 UTC, anagstef commented on .changeset/real-fans-fry.md
> +---
We need a changeset here! It's a change that impacts the customers.

2024-12-02 09:13 UTC, anagstef commented on .changeset/real-fans-fry.md
> +---
It looks like this will not have an impact.

2024-12-02 09:15 UTC, merged