feat(i18n): Update translations for multiple languages (BE, BG, CA, C…
clerk/javascript pull request #4697
Opened 2024-12-03 11:18 UTC by NavidJalilian

This pull request includes updates to the language files for various locales in Clerk. These updates aim to improve the accuracy and consistency of translations for multiple languages, ensuring a better user experience across different regions.

The languages updated in this PR include:

1. French (FR)
2. German (DE)
3. Spanish (ES)
4. Italian (IT)
5. Dutch (NL)
6. Portuguese (PT)
7. Turkish (TR)

Changes Introduced:

- Updated translation files for each of the aforementioned languages, including user-facing strings in authentication and user account management flows.
- Consistency improvements for some existing translations and more precise language usage to match the application's tone and context.

How to Test:

1. Pull the changes from this branch into your local development environment.
2. Verify the translations in the UI for each of the affected languages.
3. Ensure that the placeholders, form field hints, and other UI text display correctly in each language.
4. Test language switching functionality to ensure all new translations are being used properly. You can manually switch the UI language to check the correctness of the translations in each language file.

## Checklist

- [x]  `pnpm test` runs as expected.
- [x]  `pnpm build` runs as expected.
- [ ]  (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ]  (If applicable) [Documentation](https://github.com/clerk/clerk-docs) has been updated

## Type of change

- [ ]  🐛 Bug fix
- [x]  🌟 New feature (Localization updates)
- [ ]  🔨 Breaking change
- [ ]  📖 Refactoring / dependency upgrade / documentation
- [ ]  other:

2024-12-16 11:35 UTC, anagstef commented
Hello! Thank you for contributing! I'm assuming that something has gone wrong with the syncing of your branch. Unfortunately, it seems to be out of date, and the localizations mentioned in the PR description are missing.

2024-12-16 11:37 UTC, anagstef requested changes
Hello! Thank you for contributing! I'm assuming that something has gone wrong with the syncing of your branch. Unfortunately, it seems to be out of date, and the localizations mentioned in the PR description are missing.

2024-12-16 11:38 UTC, anagstef commented on .changeset/quiet-ducks-vanish.md
> +'@clerk/localizations': major
Also, this should not bump the major version of the package.

2025-01-22 17:24 UTC, tmilewski commented
Hey @NavidJalilian! Thanks again for submitting this. Given all of the conflicts, I'm going to close this for now. Please feel free to re-open with the reflected changes based on the latest from the `main` branch.

2025-01-22 17:24 UTC, closed without merging